name: Notify slack action
description: Send a Slack notification on failure

inputs:
  action-name:
    required: true
    description: 'The name of the action'
  webhook-url:
    required: true
    description: 'The Slack webhook URL'

runs:
  using: "composite"
  steps:
    - name: Send failure notification to Slack
      shell: sh
      run: |
        REPO_URL="${{ github.server_url }}/${{ github.repository }}"
        BRANCH="${{ github.ref_name }}"
        # Construct the workflow file URL (adjust path as needed)
        WORKFLOW_URL="$REPO_URL/blob/$BRANCH/.github/workflows/${{ inputs.action-name }}.yml"

        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "The following action workflow run has failed. :x:",
          "attachments": [
            {
              "color": "#ff0000",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Action:* `${{ inputs.action-name }}`\n*Status:* Failed :warning:\n*Job:* `${{ github.job }}`\n*Workflow:* '"$WORKFLOW_URL"'\n*Branch:* `${{ github.ref_name }}`"
                  }
                }
              ]
            }
          ]
        }' ${{ inputs.webhook-url }}
