name: Notify slack action
description: Send a Slack notification on failure

inputs:
  action-name:
    required: true
    description: 'The name of the action'
  webhook-url:
    required: true
    description: 'The Slack webhook URL'

runs:
  using: "composite"
  steps:
    - name: Send failure notification to Slack
      shell: sh
      run: |
        REPO_URL="${{ github.server_url }}/${{ github.repository }}"
        BRANCH="${{ github.ref_name }}"
        # Construct the workflow file URL (adjust path as needed)
        WORKFLOW_URL="$REPO_URL/blob/$BRANCH/.github/workflows/${{ inputs.action-name }}.yml"

        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "The following action workflow run has failed. :x:",
          "attachments": [
            {
              "color": "#ff0000",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Action:* `${{ inputs.action-name }}`\n*Status:* Failed :warning:\n*Job:* `${{ github.job }}`\n*Workflow:* '"$WORKFLOW_URL"'\n*Branch:* `${{ github.ref_name }}`"
                  }
                }
              ]
            }
          ]
        }' ${{ inputs.webhook-url }}

# name: 'Failure notification'
# description: 'Send a webhook notification when a step fails'
# inputs:
#   webhook-url:
#     description: 'The webhook URL to notify'
#     required: true
#   action-name:
#     description: 'The name of the failed step'
#     required: true
# runs:
#   using: 'composite'
#   steps:
#     - run: |
#         REPO_URL="${{ cloudbees.scm.repositoryUrl }}"
#         # Remove the .git suffix from the repo URL (if present)
#         REPO_URL_CLEAN=${REPO_URL%.git}
#         # Construct the final URL
#         WORKFLOW_URL="$REPO_URL_CLEAN/blob/${{ cloudbees.scm.branch }}/.cloudbees/workflows/${{ inputs.action-name }}.yml"

#         # Send the notification to Slack channel
#         curl -X POST -H 'Content-type: application/json' --data '{
#           "text": "
#           The following action workflow run has failed. :x:",
#           "attachments": [
#             {
#               "color": "#ff0000",
#               "blocks": [
#                 {
#                   "type": "section",
#                   "text": {
#                     "type": "mrkdwn",
#                     "text": "*Action:* `${{ inputs.action-name }}`\n*Status:* Failed :warning:\n*Job:* `${{ job.id }}`\n*Workflow:* '"$WORKFLOW_URL"'\n*Branch:* `${{ cloudbees.scm.branch }}`"
#                   }
#                 }
#               ]
#             }
#           ]
#         }' ${{ inputs.webhook-url }}