name: Gitleaks scan

on: [workflow_dispatch]

jobs:
  gitleaks-codescan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    outputs:
      gitleaks-job-output-critical: ${{ steps.gitleaks-step.outputs.critical-count }}
      gitleaks-job-output-very-high: ${{ steps.gitleaks-step.outputs.very-high-count }}
      gitleaks-job-output-high: ${{ steps.gitleaks-step.outputs.high-count }}
      gitleaks-job-output-medium: ${{ steps.gitleaks-step.outputs.medium-count }}
      gitleaks-job-output-low: ${{ steps.gitleaks-step.outputs.low-count }}
      
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print GITHUB_RUN_ID
        shell: bash
        run: |
          echo "Ref name is $GITHUB_RUN_ID"
          echo "Source is ${{ github.server_url }}/${{ github.repository }}"
          echo "Subject is $GITHUB_WORKFLOW_REF|${{ github.run_id }}|${{ github.run_attempt }}|${{ github.run_number }}"
          echo "Job is $GITHUB_JOB"
          echo "Step id is ${{ steps.internal.id }}"

      - id: gitleaks-step
        name: Gitleaks scan
        uses: cloudbees-io-gha/gitleaks-scan-publish@v1

      - id: print-outputs-from-gitleaks-step
        name: Print outputs from upstream gitleaks step
        shell: bash
        run: |
            #printing all outputs
            echo "Outputs from upstream gitleaks step:"
            echo "Critical Count: ${{steps.gitleaks-step.outputs.critical-count}}"
            echo "Very High Count: ${{steps.gitleaks-step.outputs.very-high-count}}"
            echo "High Count: ${{steps.gitleaks-step.outputs.high-count}}"
            echo "Medium Count: ${{steps.gitleaks-step.outputs.medium-count}}"
            echo "Low Count: ${{steps.gitleaks-step.outputs.low-count}}" 
